[versions]
activityCompose = "1.12.1"
agp = "8.13.2"
composeBom = "2024.09.00"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
hilt = "2.57.1"
hilt-navigation-compose = "1.1.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
kotlin-serialization = "1.9.0"
ksp = "2.3.2"
lifecycleRuntimeKtx = "2.10.0"
material3 = "1.4.0"
navigation3 = "1.0.0"
navigation3-lifecycle-viewmodel = "2.10.0"
uiText = "1.9.5"

[libraries]
# AndroidX Core maybe?
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "navigation3-lifecycle-viewmodel" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation3" }

# AndroidX testing kits.
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Compose BOM.
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }

# Build Logic.
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Kotlin.
kotlin-seralization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

# Hilt.
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Hilt.
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Ksp.
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Build Logic.
heaven-from-android-application = { id = "heaven.from.android.application" }
heaven-from-android-library = { id = "heaven.from.android.library" }
heaven-from-compose = { id = "heaven.from.compose" }
heaven-from-hilt = { id = "heaven.from.hilt" }
heaven-from-kotlin-serialization = { id = "heaven.from.kotlin.serialization" }
